README.md

TestCommit

---

Gemfile
Gemfile.lock
config/unicorn.rb

Gemfile branch

---

README.md

[WIP]Readme userテーブル関連製作

---

.gitignore
Capfile
Gemfile
Gemfile.lock
config/deploy.rb
config/deploy/production.rb
config/deploy/staging.rb
config/environments/production.rb
config/unicorn.rb

・自動デプロイの準備
・capistrano導入
Capistrano関連のGemをインストール
Capfileを編集
・デプロイについて設定ファイルの編集
config/deploy/production.rb
config/deploy.rb
capistrano(3.11.1) gemfile.lock確認済
・unicorn.rbの記述を編集
Capistranoを使った為、数カ所変更を加える必要

Unicorn edit branch(その他)

---

app/controllers/application_controller.rb

・本番環境にBasic認証機能を実装
・本番環境のメルカリに、誰でもアクセスできる状態である為、
誤ってアクセスしたユーザーに誤解を生むことがない様、
Basic認証を導入して閲覧できるユーザーを制限する。

BasicAuthenticationCommit

---

app/controllers/application_controller.rb

・Basic認証の編集を行なった
・意図した動作にならなかった為
・現在の環境が本番環境ならtrue、そうでないならfalseを返すように、
・if: :production?と記述することによって、本番環境のみでbasic_authメソッドが実行される様にする

[WIP]UpdateApplicationControllerCommit

---

app/views/users/index.html.haml

CommitInit

---

Gemfile
Gemfile.lock
app/assets/javascripts/signup.coffee
app/assets/stylesheets/signup.scss
app/controllers/signup_controller.rb
app/helpers/signup_helper.rb
app/models/user.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20190925051020_devise_create_users.rb
db/schema.rb
test/controllers/signup_controller_test.rb
test/fixtures/users.yml
test/models/user_test.rb

[WIP]deviseStartUpCommit

---

app/views/shared/_main-header.html.haml
config/routes.rb

・Topページから新規会員登録のルーティングを編集した
・製作したページを繋ぐ為

remakeCommit

---

app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/views/users/profile.html.haml
config/routes.rb

ユーザーの名前とプロフィール説明を書き換えることができる
ユーザーは名前と説明を書き換えたいことがあるから。

[WIP]edit-profile-view

---

app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/views/users/logout.html.haml
config/routes.rb

ユーザーがログアウトできるようにする
ユーザーのアカウントの自由度を上げるため

[WIP]logout-page

---

app/assets/stylesheets/users.scss
app/views/users/check.html.haml

ユーザーの住所の登録をするformをつくる
購入品の送り先情報を保存しておくことで商品購入をスムーズにするため

[WIP]Identification form

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/items/main-page.scss
app/assets/stylesheets/mixin/variables.scss
app/assets/stylesheets/modules/_item-exhibit-button.scss
app/assets/stylesheets/modules/_main-header.scss
app/views/items/index.html.haml
app/views/shared/_item-exhibit-button.html.haml
app/views/shared/_main-header.html.haml

トップページ　現時点での実装
コードレビュー前　細部修正
出品ボタン　render にて切り分け
variables　内容追加
ヘッダー修正　現時点でできる最低限のもの
[![Image from Gyazo](https://i.gyazo.com/5b79b2efbe55765cbd1e7516ec3881b4.png)](https://gyazo.com/5b79b2efbe55765cbd1e7516ec3881b4)
[![Image from Gyazo](https://i.gyazo.com/de42cfd6c50f5bf2cc34b77a18e8c267.png)](https://gyazo.com/de42cfd6c50f5bf2cc34b77a18e8c267)
[![Image from Gyazo](https://i.gyazo.com/1627c629ad14204b153ca46fff0ac319.jpg)](https://gyazo.com/1627c629ad14204b153ca46fff0ac319)
[![Image from Gyazo](https://i.gyazo.com/b5086c8d61c645745e66babf981f3548.gif)](https://gyazo.com/b5086c8d61c645745e66babf981f3548)

トップページビュー実装

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/items/buy.scss
app/controllers/items_controller.rb
app/models/user_profile.rb
app/views/items/buy.html.haml
config/routes.rb

購入確認画面が表示できる
購入するときに情報の変更ができるようにするため

[WIP]Buy confirmation

---

app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/views/users/card.html.haml
app/views/users/card_create.html.haml
config/routes.rb

クレジットカードを登録できるようにする
#Why
予め登録しておくことで購入をスムーズにする

[WIP]Credit card view

---

app/assets/stylesheets/users.scss
app/controllers/users_controller.rb
app/views/users/card.html.haml
app/views/users/card_create.html.haml

クレジットカードを登録できるようにする
予め登録しておくことで購入をスムーズにする

[WIP]credit-card_resistar

---

README.md

DB　ReadMeの内容修正
ER図　カラム名修正
itemsテーブル　カラム名変更
status →　condition　に変更
Active_hashを使用するため
カラム型をintegerに変更
|shipping_fee_burden|integer|null:false|
|shipping_method|integer|null:false|
|shipping_duration|integer|null:false|

DB Readme　ER図修正　#2

---

README.md

Update README.md #3

---

README.md

Readme modification#3

---

app/views/users/_side_bar.html.haml

マイページの"出品する"のボタンを押した時、画面遷移先を出品画面に変更。
出品できる様にする為

サイドメニューのビューファイルを更新

---

Gemfile
Gemfile.lock
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/registrations_controller.rb
app/models/sns_credential.rb
app/models/user.rb
app/views/users/registrations/index.html.haml
app/views/users/registrations/profile.html.haml
app/views/users/sessions/new.html.haml
config/initializers/devise.rb
config/routes.rb
db/migrate/20191007080706_create_sns_credentials.rb
db/schema.rb
spec/factories/sns_credentials.rb
spec/models/sns_credential_spec.rb
spec/rails_helper.rb

sns認証を実装する。facebook,googleアカウントで可能にする。
他のプラットフォームと情報を紐付けることで、ユーザーに新規登録とログインをしやすくしてもらうため。

[WIP]Sns credential

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/modules/_breadcrumbs.scss
app/assets/stylesheets/users.scss
app/views/users/completed.html.haml
app/views/users/index.html.haml
app/views/users/logout.html.haml
app/views/users/product.html.haml
app/views/users/profile.html.haml
app/views/users/progress.html.haml
config/breadcrumbs.rb

上位の階層となるWEBページを階層順にリストアップしてリンクを設置する。
ユーザーが現在どの位置にいるのか視覚的にわかりやすくするため

[WIP]Breadcrumbs

---

app/assets/stylesheets/users.scss
app/controllers/card_controller.rb
app/views/card/new.html.haml
app/views/card/show.html.haml
app/views/users/card.html.haml
config/routes.rb

・カード削除画面の調整
・カード登録画面の調整
・見本と同じにする

creditView

---

app/controllers/items_controller.rb
app/controllers/users/registrations_controller.rb
app/models/item.rb
app/views/card/new.html.haml
app/views/items/show.html.haml
app/views/users/_side_bar.html.haml
config/routes.rb

Category set up

---

app/controllers/items_controller.rb
app/controllers/users/registrations_controller.rb
app/models/address.rb
app/models/item.rb
app/models/shipping_duration.rb
app/models/shipping_fee_burden.rb
app/models/shipping_method.rb
app/views/items/new.html.haml
app/views/items/show.html.haml
app/views/users/registrations/address.html.haml
db/migrate/20191010082249_rename.rb
db/migrate/20191010082708_rename_active_hash.rb
db/migrate/20191010095251_rename_region.rb
db/migrate/20191010110402_rename_address.rb
db/schema.rb

[WIP]Product detail show

---

app/controllers/items_controller.rb
app/controllers/users/registrations_controller.rb
app/views/items/show.html.haml
app/views/users/registrations/address.html.haml
app/views/users/registrations/profile.html.haml
app/views/users/sessions/new.html.haml

・カテゴリーの表示を正しくだせるようにした。
(孫カテが取得出来ず)
・更新処理カテゴリーIdが取れなかった
・Items_Controllerのdef params_new内のmarge()内を修正して更新出来るようにした。

modifiCategoryCommit

---

app/models/image.rb
app/models/item.rb
db/seeds.rb

・Image無しの時出品出来てしまう
・ItemModelにvalidatesをかけた

noImageEdit

---

Gemfile.lock
app/assets/javascripts/items.js
app/assets/stylesheets/items/sell-item-exhibition.scss
app/controllers/items_controller.rb
app/models/item.rb
app/views/items/new.html.haml
app/views/shared/_error_message.html.haml
config/application.rb
config/locales/item.ja.yml

出品ページのバリデーション追加
出品ページのバリデーション修正が必要であったため
未入力項目があった場合、赤文字にてエラーメッセージを表示

validation-updated

---

app/controllers/items_controller.rb
app/views/items/_main_product_boxes.html.haml
app/views/items/new.html.haml

全ての新着アイテムとしてトップページに表示する項目追加
カテゴリーにかかわらず、新規出品商品１０件を表示させるため

Modified-top-page-contents

---

app/assets/javascripts/scroll.js
app/assets/javascripts/sliders.js
app/assets/stylesheets/items/sell-item-exhibition.scss
app/assets/stylesheets/modules/_main_product.scss
app/controllers/items_controller.rb
app/views/items/_main_product_boxes.html.haml
app/views/items/_main_product_nav.html.haml
app/views/items/new.html.haml
app/views/shared/_error_message.html.haml

トップページ人気カテゴリーボタン押下によるページ内指定位置スクロール機能追加
家電スマホカメラの項目をトップページに追加
ボタン押下による、画面内指定位置ジャンプ機能を追加し、ページ内の表示アイテムが増えても探しやすくするため。

scroll-function-added

---

app/models/category.rb
app/models/image.rb
app/models/item.rb
app/models/size.rb

seed-file-execution
